query Friends {
  friends {
    id
    status
    sender {
      id
      username
      email
      sex
      interests
      aboutMe
      age
      occupation
      avatar
    }
    receiver {
      id
      username
      email
      sex
      interests
      aboutMe
      age
      occupation
      avatar
    }
  }
}
